### PR TITLE
Bring up to date, add s3 download flow from Rails PR, Github Actions

### PR DESCRIPTION
**Pull request by ssunday**
Taken from code done in: https://github.com/rails/rails/pull/39364, authors:

- *Bob Farrell* (@bobf )
- *Chris Ortman* (https://github.com/chrisortman) 
- *Marco Borromeo* (??)
- Me

Not sure how we need to handle authors, notifying them of this/updating the gem spec ??. 

Added github actions setup to test with, not sure if we want that.

Have not e2e tested it yet, will get to that soon, but feel ... moderately confident lol.

### CODE REVIEW

**Comment by bobf** [comment]
@ssunday Great, thanks a lot. If you feel like picking up the aws-sdk PR at any point then please feel free, otherwise I'll see if I can find some time to do that. Thanks a lot for the PR, I think best to wait until e2e testing is done, which I'm also happy to do if you don't have time, but will likely be next week earliest.

**Comment by ssunday** [comment]
@bobf I'm going to try to get the e2e testing done this week if not today, assuming priorities don't change.

**Comment by ssunday** [comment]
It works!

**Comment by bobf** [comment]
@ssunday Hooray ! Thank you for all the work getting this ready. 

Also sorry for confusing things with aws-sdk - I feel I gave the impression that I was expecting you to do this work as well, was just including you in the conversation in case you were interested in doing that, but no expectation from me whatsoever.

I'll pick up next week and at least try to make a PR to get the ball rolling but it sounds like we both are pretty busy at the moment so it might just be easier to give the aws-sdk author our blessing to take our work and merge it in, but the library is MIT-licensed for a reason. : )

**Comment by ssunday** [comment]
@bobf Oh no worries, thank you so much! I just wanted to make it clear like my goal scope haha. The fire was hot for this reason... 

I might also try to do a PR at some point, definitely would make my project's dependency list simpler, but we'll see how things go. I'll definitely keep everyone posted if I do decide to pick it up so we don't dupe work 😂

**Comment by bobf** [comment]
@ssunday I just realised I didn't release a new version of the gem after your additions.

Since quite a lot of stuff has changed I've bumped the minor version, so latest version is now [0.2.0](https://rubygems.org/gems/action_mailbox_amazon_ingress/versions/0.2.0)

**Pull request merged**
